import { ScrollView, StyleSheet, Text, View } from 'react-native'
import React from 'react'

const License = () => {
  return (
    <ScrollView>
    <View>
      <Text>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi aliquam doloribus, dolorem quos, minima minus quasi reiciendis nemo nobis incidunt, rem maiores consequuntur debitis. Non dolore dolorem ipsam cupiditate ut! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam quod iste nihil rem quaerat exercitationem eaque architecto, accusamus sapiente sunt assumenda laborum, aperiam vitae sit suscipit ducimus nulla recusandae at.lorem Lorem ipsum dolor sit amet consectetur, adipisicing elit. Amet eligendi soluta velit dolorum! Asperiores fuga illum error quis placeat architecto nostrum. Ab fugiat debitis tempora suscipit impedit explicabo accusamus quas. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorem omnis, magnam inventore numquam consequatur sequi unde sunt atque accusamus dignissimos iste officia, repellendus sed aspernatur, excepturi necessitatibus placeat minima rerum.
      Architecto rem voluptatum repudiandae autem alias veniam accusantium harum quibusdam maiores vero aperiam aliquam quidem, officiis dolore commodi assumenda pariatur, dicta accusamus magni repellat consectetur facilis quisquam necessitatibus iure. Voluptate.
      Quae, exercitationem. Dolorem sit cum inventore vero consequuntur, a debitis amet ipsam distinctio eos explicabo quos, quae at, praesentium deserunt magni vitae delectus laborum quod aperiam illum. Libero, cupiditate aliquam?
      Deserunt neque impedit pariatur sapiente, ratione fugiat nulla natus eaque minima repellat quia molestiae necessitatibus quaerat aliquid, quam accusantium atque repudiandae architecto odit est sint consequatur! Ducimus odio incidunt ut?
      Consequuntur, recusandae? Labore quos sapiente ea odit dolor nihil itaque sed impedit cumque sequi aliquam, nemo amet enim minus eligendi, omnis sit molestias sint est, velit soluta distinctio ipsa! Distinctio.
      Sed tempore possimus consequuntur animi, sunt voluptatem eum excepturi, soluta nemo iste dolor commodi est praesentium porro perspiciatis rerum repellendus quasi dicta iure reiciendis debitis! Tempora fugit unde in obcaecati?
      Accusantium nisi ex modi quidem corrupti veritatis, blanditiis quod reiciendis dicta enim officiis possimus in alias est accusamus ducimus deleniti a odit, iure eius nostrum nulla inventore consequatur magni? Fugit.
      Assumenda alias ullam, quas distinctio veniam at amet? Laboriosam odio pariatur saepe! Aliquam mollitia non ut sint voluptas illum, quis debitis dolorem nemo porro quam eaque molestias recusandae perspiciatis. Praesentium?
      Commodi pariatur corporis illum sed eaque qui officia esse, cumque ipsam nemo tempora eum minus, ipsum totam enim. Aspernatur ullam sed iste vitae illo earum quas aliquid, dolore recusandae ipsa!
      Vero vel blanditiis, perspiciatis quasi praesentium esse aut laudantium, dolorem laboriosam, debitis alias inventore dolores? Fugiat consectetur voluptates libero dolores. Harum minus exercitationem reprehenderit aut saepe fugiat, commodi iusto sint!
      Amet tenetur, omnis ullam alias error harum atque adipisci illo unde, labore quibusdam vitae provident obcaecati hic impedit maiores natus? Nobis quis reiciendis est commodi dolore quaerat debitis, nesciunt distinctio.
      Amet ullam eligendi rerum a. Eum fugit velit molestias accusamus quibusdam, cumque aliquam ratione quisquam qui, ipsum voluptatum? Autem aliquam molestias omnis temporibus amet nulla, rerum minima minus totam iusto.
      Autem doloribus, fuga sit alias repellat sed aliquid. Rem molestias necessitatibus asperiores quis ratione repellendus, dolorem perspiciatis ipsum, est eum vero voluptates, non maiores voluptate temporibus numquam dignissimos impedit ea.
      Nostrum labore mollitia exercitationem dolorum dolor est vero maiores quas quasi, distinctio ducimus quibusdam et! Soluta exercitationem odit necessitatibus eos, est, laborum velit porro aliquam, dignissimos similique sunt quas. Deleniti?
      Fugiat tempore quibusdam magnam officiis, voluptates quae repudiandae deleniti qui quo culpa alias. Deserunt harum quidem quo aspernatur asperiores facere eos ex, sequi illo ab sit corporis, fugiat minima dolorem.
      Minima minus expedita ipsa possimus voluptas tempora, nesciunt quas quos soluta? Aut iste eveniet odio facere distinctio deleniti est, sequi, autem ullam dicta dolorum consectetur officia nihil nesciunt quibusdam fuga?
      Officia natus iste perferendis ducimus omnis provident laudantium sint beatae architecto! Maxime magnam quas impedit laudantium, dicta delectus quibusdam libero minus in. Quod enim nam natus omnis ipsum? Illo, eius.
      Itaque dolorum error, numquam quod dolorem ex nam et aliquid praesentium. Magnam modi ex natus, harum fuga velit, explicabo accusantium voluptatibus recusandae nesciunt dicta non doloremque, dolorem obcaecati accusamus temporibus?
      Distinctio sunt saepe ipsa, voluptas odit, iusto, exercitationem ab maxime rem quia aut repellat placeat illo labore vitae velit perferendis! Suscipit fugit totam cumque illo, officiis similique corrupti? Dolorem, consectetur.
      Tenetur culpa earum reiciendis adipisci veniam necessitatibus voluptate error repudiandae, assumenda, nesciunt totam est ab eveniet numquam molestiae pariatur ea deserunt corrupti eius at facilis aperiam minima perspiciatis ducimus! Distinctio!
      Id, corporis sed obcaecati illum voluptatem, corrupti consequatur quas consectetur quod officiis illo molestiae sint ullam. Aspernatur dolorum accusamus fugit optio error atque praesentium. Doloribus voluptates quos neque cumque natus.
      Error nemo velit magni pariatur qui voluptatibus accusantium, aliquid ea fugiat veniam commodi eius dolorem optio quis expedita, obcaecati sapiente saepe provident eos doloribus consectetur. Totam voluptatum eveniet quibusdam iste!
      Voluptatum animi, aliquid necessitatibus minima sed natus nulla. Veritatis aliquid culpa voluptate maiores dicta quam, reprehenderit quisquam suscipit, molestias inventore alias adipisci ipsum, in reiciendis est hic. Odio, aliquid facilis?
      Laborum ab dignissimos quia? Minus, est a vel nam aperiam ducimus voluptates qui tempora culpa sed similique debitis labore atque optio, odio temporibus, consequuntur voluptatibus ipsa voluptatem. Praesentium, blanditiis sed.
      Dolor illo animi ullam possimus iusto vel veniam pariatur quae eaque! Labore distinctio praesentium molestiae corrupti cum? Non laborum ea deserunt aspernatur rerum autem nihil, corrupti molestias, facere quaerat sint.
      Reiciendis minima sunt amet quisquam officia ut magni fuga. Amet aliquam officia nesciunt impedit accusamus quisquam ducimus quia, possimus molestias quis perspiciatis harum assumenda debitis sunt perferendis. Modi, aspernatur quidem.
      Dolores id esse ipsam aut optio suscipit quia reprehenderit ipsum, blanditiis rerum nulla iure accusamus tempora? Consectetur laborum quas adipisci voluptatem cumque accusamus magni quia et, asperiores eos molestiae tempore.
      Nisi aut sequi placeat in earum nostrum impedit odit natus, quae laudantium, voluptates eos doloremque eum dicta temporibus ab beatae, error consequuntur. Dolores molestiae doloribus iste tempora esse nobis in?
      Dolores tenetur error, a hic totam accusantium nihil vero? Tempore, ipsam! Obcaecati aliquid amet provident laboriosam nobis molestias repellat. Minus nesciunt officiis repellat nobis et natus nam iusto dolores omnis!
      Nam veritatis atque magnam voluptatem esse velit ex commodi rem asperiores libero sit ipsa, minima, numquam quod. Est repellat autem expedita consequuntur sunt qui quae doloremque. Mollitia consectetur dolore perspiciatis!
      Esse laboriosam fugit totam ducimus laudantium quis ad magnam ab ipsum impedit alias tempore quas eveniet illum vitae odit iusto debitis, illo doloribus! Itaque accusamus possimus repellendus modi provident pariatur.
      Animi natus deleniti porro fuga laborum labore molestias repudiandae rerum unde accusantium, inventore nihil culpa, vitae fugit impedit vel quibusdam quaerat quasi quam minus hic. Quisquam in sint nobis fuga.
      Accusamus culpa quas fuga atque neque, placeat recusandae nulla ullam provident eos tempore ipsum eveniet, quasi deserunt quibusdam nemo commodi praesentium, corporis tempora dolorem repudiandae saepe nobis illo! Doloremque, voluptates.
      Laboriosam laborum ratione necessitatibus ut, odit, suscipit maiores commodi id praesentium, quam libero accusantium assumenda deleniti tenetur esse earum reiciendis quisquam! Tempore corporis omnis magnam! Et animi labore sint corrupti.
      Ipsam quam obcaecati, saepe vitae ipsum ducimus tempora libero aliquam, similique eius, neque tempore? Illum earum inventore voluptatibus nostrum labore excepturi iste, obcaecati unde reiciendis, maxime aliquam praesentium laudantium fugiat?
      At soluta quisquam temporibus porro nesciunt illo voluptatum voluptates doloremque possimus magnam corporis, sapiente ratione, nisi commodi fugit adipisci? Neque et, commodi nisi quam voluptates distinctio nostrum accusantium dignissimos odio?
      Ea modi atque qui officia adipisci soluta harum obcaecati, ab dolorem veritatis repudiandae magnam pariatur recusandae sint quae, maiores cupiditate laborum nihil perspiciatis corrupti sequi aliquid ut, et expedita. Neque.
      Aliquid delectus aperiam expedita repudiandae quibusdam animi exercitationem minus consectetur quasi? Vel ducimus doloremque accusantium laudantium deserunt reiciendis exercitationem. Dolore, minus dolorum odit animi sunt libero non minima necessitatibus eius.
      Voluptatibus maiores totam perferendis quam, aut consectetur. Expedita ullam reprehenderit corrupti iure id nostrum atque et autem deserunt dolore, officiis sit ex alias repellat, quo nobis? Eos ipsam eius voluptatum.
      Modi distinctio accusantium sapiente delectus temporibus perferendis libero vitae ea voluptate nulla, corporis ab molestiae in possimus sunt officia. Possimus consequatur accusamus mollitia soluta magnam est, repellendus obcaecati. Ex, explicabo.
      Sint nihil odit libero saepe id doloremque accusamus incidunt odio eos suscipit? Est, quo. Inventore assumenda voluptas excepturi, dignissimos minima, nesciunt repellat necessitatibus veniam deleniti reiciendis, dolore magnam commodi qui.
      Rem porro, et amet saepe, iste blanditiis explicabo eveniet exercitationem delectus eos modi minus iusto aliquam facilis pariatur aliquid ad ullam natus quis quam. Sapiente nulla nobis maiores tempora ut!
      Tempora repudiandae nobis id sequi, eaque corporis a harum hic, explicabo atque commodi. Quos ea mollitia alias, enim inventore et ipsam neque totam dolorem ducimus tenetur doloremque, a dolores amet.
      Officiis porro ab, asperiores ipsam fugiat sed ad aut nisi fugit laudantium, quis quibusdam dolor consequatur voluptatibus. Nobis modi sequi, sunt aspernatur doloribus ad suscipit, ipsum tempora perferendis incidunt error.
      Recusandae aut labore voluptatem expedita voluptate voluptatibus quasi placeat animi, tempore dolorum ratione, nostrum alias qui, hic quisquam quis distinctio necessitatibus ut amet eligendi obcaecati minima libero ea facilis! Perferendis?
      Iure aperiam est non dolorem deserunt provident molestias modi. Quasi, reiciendis quia ipsa aperiam temporibus voluptatem labore voluptate sint vitae adipisci itaque quod voluptas hic minus expedita voluptates aliquid laudantium.
      Facere omnis optio neque obcaecati, cupiditate deleniti error magni reprehenderit sed tenetur in repellendus eligendi a voluptatum nemo sit distinctio eos molestiae ad. Quas, libero quisquam cupiditate dolores harum esse!
      Vel nam odit mollitia animi excepturi, ad corporis obcaecati architecto illo, libero natus ipsum? Atque dolor nulla eveniet architecto libero ipsam perferendis optio dolores, enim voluptate velit ipsum exercitationem corrupti.
      Sit et porro ea omnis laboriosam id atque possimus optio consequuntur quos rerum, esse reprehenderit officiis similique, alias minima rem architecto. Eum, magni fuga sapiente omnis veniam optio unde laudantium.
      Tenetur, esse nulla porro cum eos minima non vitae consectetur nesciunt enim quam incidunt animi nobis deleniti minus a excepturi libero, reprehenderit, sapiente repellendus. Corporis quibusdam earum dolores ad inventore.
      Hic beatae incidunt facere perferendis ipsa at, doloribus aspernatur officia et! Consequatur nemo quod tempora ab praesentium pariatur exercitationem repellendus ipsam impedit. Repellendus, dignissimos excepturi odio esse voluptates quos officia.
      Maiores pariatur quo ea, velit sapiente eum earum quia eaque nobis, repudiandae nesciunt impedit suscipit quae vel numquam perspiciatis unde ex quibusdam nihil optio aliquid. Accusamus debitis quidem beatae nostrum?
      Accusantium dignissimos nam, consectetur minus tenetur ipsa! Eaque sint consectetur ea incidunt nulla quis ad excepturi aut sapiente, in ipsum, minima mollitia deserunt soluta? Ex laudantium doloribus nam eum facere.
      Impedit accusantium, veritatis officia aspernatur odit aliquam voluptate deleniti eaque dolores voluptates dolorem quisquam corrupti soluta maxime accusamus laborum suscipit nobis adipisci cum consequatur mollitia ipsam minima dolore! Saepe, deleniti.
      Dolore in soluta magnam quisquam vero? Dolores molestias eaque earum voluptatum a aliquid ad sapiente, molestiae quisquam ut itaque voluptatibus corporis qui, eum suscipit quibusdam maxime nesciunt nihil facilis nobis.
      Eveniet cum at similique culpa, quos ratione mollitia reprehenderit placeat corrupti odit optio nemo itaque, sit minima, accusamus voluptatem enim doloremque assumenda. Tenetur nesciunt similique dolores voluptates ipsum obcaecati esse.
      Tempora ea nulla veniam tenetur, necessitatibus quod exercitationem cupiditate voluptas perspiciatis molestiae facilis officia architecto maxime non corporis aperiam illo temporibus voluptatibus impedit assumenda provident optio? Excepturi officiis ut rerum?
      Alias nobis vitae voluptas, omnis cum exercitationem deleniti doloremque vel non vero incidunt voluptatum modi cupiditate accusantium beatae molestiae nihil debitis repellendus commodi dolor quas in voluptate hic. Est, rem.
      Pariatur harum minus ab, adipisci consectetur iusto numquam dolor omnis corrupti impedit quia culpa rerum deserunt. Autem deleniti perferendis, quaerat pariatur molestiae praesentium, doloribus voluptas quis, ut quos ea omnis.
      Nihil commodi et modi sequi obcaecati labore quibusdam quisquam, magni deleniti ea architecto ratione. Sit at nostrum aperiam odio iure architecto alias corrupti voluptatum voluptas, deleniti, nihil dolorem, temporibus distinctio.
      Necessitatibus ducimus harum nam consequatur ullam dolor, maxime eveniet ipsum esse consectetur minima unde asperiores quam delectus laborum. Deserunt atque esse voluptatibus ullam voluptatem explicabo nisi totam numquam quod aliquam.
      Praesentium quo aperiam asperiores debitis. Magnam pariatur reprehenderit eius qui, itaque ad impedit cumque, veritatis eos voluptatibus vitae ut ducimus hic natus provident ea quo rem repudiandae dignissimos saepe? Laboriosam.
      Cupiditate, rem ut similique hic reiciendis, placeat tenetur ratione laudantium nostrum quaerat suscipit ipsum. Assumenda at quas cum provident impedit asperiores a commodi ipsam alias esse nesciunt optio, voluptatibus error.
      Commodi aliquid, dolorum, totam labore ipsa itaque nesciunt, inventore at corporis ipsam autem. Officia, repellendus. Cum unde expedita labore nihil repudiandae eveniet recusandae tenetur. Delectus, deleniti consequatur? Tempore, vero est!
      Neque et quam libero sequi saepe adipisci nam velit, doloribus eveniet qui magnam aut repellendus incidunt dolor suscipit quae. Numquam harum incidunt rerum cum asperiores assumenda dignissimos consequuntur vitae officiis!
      Assumenda sunt soluta suscipit corporis laborum officia iste nisi. Sed dolore earum recusandae obcaecati deleniti. Iusto cupiditate voluptatem aliquid tempora. In quisquam possimus corrupti autem eius. Tempore reprehenderit magni expedita?
      Ab consectetur optio labore, animi assumenda eum delectus sapiente quas numquam? Ducimus sed dolorem animi. Impedit, animi? Magnam sint, molestiae temporibus reprehenderit quo sit perferendis non repudiandae, minima nihil eligendi?
      Praesentium facere error cumque amet doloribus quaerat aliquid ab rerum tenetur, mollitia possimus adipisci aliquam ratione provident quidem inventore consectetur quae dolorem facilis repellendus! Fugit libero possimus ratione tempora natus.
      Qui incidunt harum tempore nesciunt ipsa voluptatum quis assumenda reprehenderit quo veniam laboriosam nulla rerum dolore consequatur fugit commodi accusamus, pariatur, dignissimos iste, illum velit fugiat? Aliquam tenetur amet eius.
      Ut itaque at sunt recusandae ipsa placeat exercitationem dolore corrupti doloribus expedita hic nesciunt saepe laudantium, porro adipisci beatae magnam, odit fugit. Quo cumque distinctio, sunt inventore eveniet itaque autem.
      Cumque obcaecati sapiente dolorem sequi. Ex eligendi, magnam itaque cupiditate non temporibus, hic eveniet iste doloremque optio illo modi perferendis rerum! Eligendi aspernatur excepturi nihil autem necessitatibus quae, quidem sint!
      Accusantium sit libero quibusdam. Quo ducimus neque eius provident eum repellendus iusto? Sit molestias quod reiciendis mollitia assumenda minima. Pariatur mollitia dolorum numquam assumenda magni dignissimos, sunt tempora voluptas at.
      Cum magni necessitatibus temporibus earum repellat illo magnam tempora eius. Animi placeat cupiditate voluptates praesentium esse commodi, rem soluta quibusdam autem assumenda atque laboriosam eum reprehenderit repudiandae in? Exercitationem, quis.
      Amet, sapiente numquam ipsum laudantium cupiditate quibusdam quis veritatis possimus ullam tempora incidunt a accusantium commodi, consectetur velit at culpa repellat nostrum. Molestiae maiores cumque ad error ab dolores non?
      Harum nulla qui odit ex numquam dicta quam, atque soluta eius, voluptatibus, aut animi placeat tempora? Incidunt hic id voluptate, iusto aperiam impedit in odio dolores dolor, iste, assumenda pariatur?
      Id, minima inventore. Magnam optio accusamus maxime alias similique iusto doloribus temporibus doloremque, officiis earum veritatis iure ullam possimus aspernatur ipsum iste enim! Qui quis sint quo consequuntur debitis quia?
      Quaerat doloremque non molestiae fugiat minima assumenda cum provident, exercitationem dolor sint voluptatum reiciendis eius vitae laboriosam reprehenderit vel similique, quidem expedita ex dicta, qui ratione. Excepturi facilis nobis fugiat!
      Eveniet, sint ipsum quam vel minus accusantium eius consectetur eligendi amet aspernatur blanditiis rem autem, ex doloribus ipsa perspiciatis magnam veritatis voluptatem in, mollitia impedit repellendus nihil cumque! Sunt, nobis?
      Ipsum libero rem repellendus architecto odit deleniti illum tempora! Assumenda quos qui aliquid cumque repudiandae, voluptate similique blanditiis tempora. Quisquam, dicta suscipit. Iure iste dolore, eaque distinctio eos aperiam perspiciatis.
      Corporis minima, tempore rem quasi ipsum nesciunt nihil ullam sint modi nulla fuga dolor vero omnis maiores, voluptas in labore. Debitis animi ratione atque veniam et consectetur. Dolorum, rerum natus.
      Perferendis eum fuga excepturi, mollitia maxime commodi voluptates id? Provident optio unde aliquam repudiandae placeat, iure obcaecati ipsam voluptas ad? Dolore corrupti doloremque fugiat tempore, nobis harum voluptatem veniam incidunt!
      Dolore porro est similique praesentium. A culpa eos at impedit, enim temporibus optio sit officiis quis perspiciatis quibusdam aliquid id soluta eius accusamus ullam porro, adipisci corporis! Vel, deserunt. Suscipit?
      Cupiditate, tenetur consectetur? Quam sunt excepturi pariatur omnis voluptatibus ipsam laboriosam dolor eveniet, accusamus, rem amet nobis mollitia tenetur maiores consequatur, eum laudantium nam harum eaque cum ratione aspernatur eius!
      Adipisci, cumque amet. Velit suscipit dicta magni. Asperiores accusamus nulla nobis! Accusantium beatae cum ducimus animi provident molestias laborum quas odit rerum eos quia hic ex minus incidunt, facilis tempora.
      Voluptate fuga, nihil numquam quaerat ratione voluptatem molestias, at facilis provident fugit eveniet. Eaque iusto rem necessitatibus incidunt eos consequatur id ad, possimus error. Similique consequatur quia repellat dignissimos modi.
      Dignissimos expedita molestias a incidunt accusamus error sapiente quia repellendus modi iusto aut commodi eos, praesentium cumque unde dolorem dolor. Voluptatibus deleniti illum dolorum debitis aperiam! Mollitia rerum fuga autem.
      Impedit quo explicabo quam atque harum molestias totam quaerat unde reiciendis optio, distinctio nihil dicta magnam modi mollitia maiores fugiat numquam pariatur omnis. Est modi id voluptatum sequi, eius fuga!
      Provident similique, maxime, ut ea asperiores aliquam laudantium atque laborum harum animi sapiente pariatur porro natus facere tempore, veniam impedit nobis corporis recusandae inventore? Labore non omnis repudiandae doloribus reprehenderit!
      Eos quibusdam cum, corporis error ea eveniet in modi ex numquam omnis fugit esse beatae fugiat commodi nihil iste explicabo! Ab hic dolore tempore, minima delectus officia pariatur facere optio.
      Tempore facere minima ab explicabo aspernatur similique saepe, laudantium sunt dolor quisquam illum asperiores deserunt? Necessitatibus enim consectetur harum et, fuga, dolorem amet eveniet hic quibusdam magni nemo? Sunt, corporis?
      Eaque magni praesentium harum a velit cum enim nihil quaerat, ut reprehenderit sequi tenetur totam dolorem fuga quo quod, cumque eius dicta quas molestiae dolores exercitationem. Obcaecati voluptatem unde alias.
      Temporibus ut culpa nostrum suscipit nesciunt tempora maiores dolore expedita, quasi sapiente dolorum assumenda aliquam ullam necessitatibus odio quod? Porro architecto eius quisquam illum eveniet obcaecati nulla error eum doloribus!
      Similique natus iste inventore molestias mollitia modi temporibus. Earum, facilis eaque eos nostrum labore officiis incidunt pariatur cupiditate impedit ex ut fuga laudantium illum veritatis a non ipsa harum at?
      Voluptatibus ipsum veritatis placeat odit necessitatibus aspernatur cupiditate? Officia sint cumque eligendi temporibus facilis ratione necessitatibus exercitationem, quis cum nostrum sunt nam labore architecto. Repudiandae iste cum mollitia non ipsa?
      Veritatis, delectus. Aliquid laudantium impedit expedita quae sunt itaque consequuntur, vero assumenda ipsam ab recusandae numquam culpa corrupti, aperiam odit minus sapiente rerum. Ad, accusantium nostrum voluptatem inventore reprehenderit ipsam!
      Dolorem sequi commodi quo consectetur id quae laudantium quod rem quas sit exercitationem, nesciunt itaque velit unde? Beatae voluptates perferendis iure vero, labore delectus dignissimos quisquam laboriosam quae a quidem!
      Quisquam velit officia ab labore? Repudiandae voluptas consequuntur earum error amet, maiores nam itaque porro quasi ullam omnis recusandae sunt nemo perferendis necessitatibus expedita ad corporis maxime. Dolores, modi deleniti.
      Dolore repudiandae incidunt adipisci fugiat temporibus vero commodi dolor, ea accusamus eius! Ducimus labore perferendis maxime! Quaerat optio, aperiam consequatur in eos numquam omnis cumque fugiat. Similique dicta libero quod?
      Impedit eveniet excepturi, ratione sunt mollitia alias esse tenetur blanditiis error quidem omnis sit asperiores nobis, hic officiis possimus inventore libero earum saepe autem! Necessitatibus ad hic reiciendis quaerat assumenda.
      Laudantium expedita nihil provident quos ut accusantium natus, aperiam ad a at dignissimos, fuga sapiente perspiciatis aliquid ex, fugit officia? Qui eos blanditiis assumenda. Voluptatem cum ad praesentium porro saepe.
      </Text>
    </View>
    </ScrollView>
  )
}

export default License

const styles = StyleSheet.create({})